spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/nalsee
    username: 
    password: 
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 
            client-secret: 
            redirect-uri: 

cloud:
   aws:
    credentials:
      access-key: 
      secret-key:
